language: bash

services:
  - docker

compiler:
  - gcc

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
before_install:
    - eval "${MATRIX_EVAL}"

addons:
  apt:
    packages:
      - doxygen
      - cmake-data
      - cmake

script:
  - docker build .
  - doxygen doxygen.conf
  - mkdir build && cd build && cmake ..
  
    #deploy:
    #  provider: pages
    #  skip_cleanup: true
    #  local_dir: public
    #  github_token: $GITHUB_TOKEN
    #  keep-history: true
    #  on:
    #    branch: master
